# Generated by Django 3.2.3 on 2021-05-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100, verbose_name='nome')),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
            ],
        ),
    ]
